import { state } from "../state.js";
import { $, esc, fmt, intFmt } from "../utils.js";
import {
  buildPlayerTierModel,
  tierDescription,
  tierLabel,
} from "../tiers.js";

export function renderTiers(){
  const a=state.analysis,all=a.tierPlayers||buildPlayerTierModel(a.players||[]);
  $('#tiers').innerHTML=`<div class="panel"><div class="section-title"><div><h2>Player Tiers and Expected PPG</h2><div class="small">Composite tiers emphasize upcoming-season projection, then dynasty market value and expected career longevity.</div></div></div><div class="tier-page-controls"><input id="tierSearch" placeholder="Search player"><select id="tierPosition"><option value="">All positions</option><option>QB</option><option>RB</option><option>WR</option><option>TE</option></select><select id="tierLevel"><option value="">All tiers</option><option value="S">Tier S</option><option value="1">Tier 1</option><option value="2">Tier 2</option><option value="3">Tier 3</option><option value="4">Tier 4</option></select><select id="tierRoster"><option value="">Rostered + free agents</option><option value="Rostered">Rostered only</option><option value="Free Agent">Free agents only</option></select><select id="tierSort"><option value="composite">Sort: Composite tier score</option><option value="ppg">Sort: Expected PPG</option><option value="value">Sort: Dynasty value</option><option value="longevity">Sort: Longevity</option></select></div><div class="tier-summary">${['S','1','2','3','4'].map(t=>`<div class="tier-summary-card"><div class="tier-name">Tier ${t}</div><div class="tier-range">${esc(tierLabel(t))}</div><div class="small">${all.filter(p=>p.analysisTier===t).length} players</div></div>`).join('')}</div><div id="tierBoard"></div></div><div class="panel"><div class="section-title"><h2>Tier Methodology</h2></div><div class="tier-methodology-grid"><div class="tier-methodology-item"><strong>60% Upcoming Projection</strong>Expected PPG percentile among players at the same position. Expected PPG equals projected season total divided by 17.</div><div class="tier-methodology-item"><strong>25% Dynasty Value</strong>Consensus percentile using available RosterAudit and DynastyProcess values for the league format.</div><div class="tier-methodology-item"><strong>15% Career Longevity</strong>Age-curve score by position, adjusted for injury, role, NFL-team status, and the existing risk model.</div></div><div class="callout" style="margin-top:12px"><strong>Interpretation:</strong> These are analytical tiers created by this application, not copied rankings. Existing projection and dynasty-value sources are incorporated, while longevity is calculated internally.</div></div>`;
  ['tierSearch','tierPosition','tierLevel','tierRoster','tierSort'].forEach(id=>$('#'+id).addEventListener(id==='tierSearch'?'input':'change',renderTierBoard));renderTierBoard();
}

export function renderTierBoard(){
  const a=state.analysis;let rows=[...(a.tierPlayers||[])];const q=($('#tierSearch')?.value||'').toLowerCase(),pos=$('#tierPosition')?.value||'',level=$('#tierLevel')?.value||'',roster=$('#tierRoster')?.value||'',sort=$('#tierSort')?.value||'composite';
  rows=rows.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!pos||p.position===pos)&&(!level||p.analysisTier===level)&&(!roster||(roster==='Rostered'?p.rosterId>0:p.rosterStatus==='Free Agent')));
  const sorter={composite:(a,b)=>b.tierComposite-a.tierComposite,ppg:(a,b)=>b.expectedPpg-a.expectedPpg,value:(a,b)=>b.dynastyValue-a.dynastyValue,longevity:(a,b)=>b.longevityScore-a.longevityScore}[sort];rows.sort(sorter);
  const tiers=['S','1','2','3','4'].filter(t=>!level||t===level);
  $('#tierBoard').innerHTML=`<div class="tier-board">${tiers.map(t=>{const group=rows.filter(p=>p.analysisTier===t);if(!group.length)return '';return `<section class="tier-group"><div class="tier-group-header"><h3>Tier ${t} — ${esc(tierLabel(t))}</h3><div class="tier-explanation">${esc(tierDescription(t))} · ${group.length} players</div></div><div class="tier-player-grid">${group.map((p,i)=>`<article class="tier-player-card tier-${String(t).toLowerCase()}"><div class="tier-player-head"><div><div class="tier-player-name">#${i+1} ${esc(p.name)}</div><div class="tier-player-meta">${esc(p.position)}${p.nflTeam?` · ${esc(p.nflTeam)}`:''} · Age ${p.age??'—'} · ${esc(p.rosterStatus)}</div></div><div class="tier-score">${fmt(p.tierComposite,1)}<small>Tier score</small></div></div><div class="tier-metrics"><div class="tier-metric"><div class="value">${fmt(p.expectedPpg,2)}</div><div class="label">Expected PPG</div></div><div class="tier-metric"><div class="value">${intFmt(p.dynastyValue)}</div><div class="label">Dynasty value</div></div><div class="tier-metric"><div class="value">${fmt(p.longevityScore,0)}</div><div class="label">Longevity</div></div></div><div class="small" style="margin-top:8px">Projection ${fmt(p.projectionPct,0)}th pct · Value ${fmt(p.valuePct,0)}th pct · Longevity ${fmt(p.longevityPct,0)}th pct · ${esc(p.projectionSource)}</div></article>`).join('')}</div></section>`}).join('')}</div>`;
}
